logging:
  level:
    org:
      springframework:
        data: debug
server:
  port: 8088
spring:
  data:
    mongodb:
      database: inventory
      host: localhost
      port: 27017
  kafka:
    bootstrap-servers: localhost:9092